"""add_recurring_columns_to_tasks

Revision ID: 928813725ff7
Revises: c25b1965ba66
Create Date: 2026-05-13 09:35:43.108321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '928813725ff7'
down_revision: Union[str, None] = 'c25b1965ba66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_recurring', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('tasks', sa.Column('recurrence_rule', sa.String(length=50), nullable=True))
    op.add_column('tasks', sa.Column('recurring_time', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'recurring_time')
    op.drop_column('tasks', 'recurrence_rule')
    op.drop_column('tasks', 'is_recurring')
    # ### end Alembic commands ###
