"""add_whatsapp_number_to_users

Revision ID: c25b1965ba66
Revises: 037530ad0721
Create Date: 2026-05-08 09:34:15.439437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c25b1965ba66'
down_revision: Union[str, None] = '037530ad0721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('whatsapp_number', sa.String(length=30), nullable=True))
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_index(op.f('ix_users_whatsapp_number'), 'users', ['whatsapp_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_whatsapp_number'), table_name='users')
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('users', 'whatsapp_number')
    # ### end Alembic commands ###
